document.writeln('<footer>')
    document.writeln('<p>Bells and Whistles Band</p>')
    document.writeln('<p>123 Band Boulevard</p>')
    document.writeln('<p>New York, NY 10023</p>')
    document.writeln('<span>&nbsp;</span>')
    document.writeln('<p>(123) 456-7890</p>')
    document.writeln('<p>booking@bellsandwhistlesband.com</p>')
    document.writeln('<p>IG: @bellsandwhistlesband</p>')
document.writeln('</footer>')