document.writeln('<a href="index.html">')
    document.writeln('<img src="images/logo.png" alt="Website Logo" name="logo" class="logo">')
document.writeln('</a>')
document.writeln('<div id="nav" name="nav" class="nav">')
    document.writeln('<ul>')
        document.writeln('<li><a href="index.html">Home</a></li>')
        document.writeln('<li><a href="about.html">About</a></li>')
        document.writeln('<li><a href="songs.html">Songs</a></li>')
        document.writeln('<li><a href="contact.html">Contact</a></li>')
    document.writeln('</ul>')
document.writeln('</div>')
